### ISSUE TITLE
Android group call throwing exception

### ISSUE THREAD

**Issue by NeerajRai111** [Laerdal/Xamarin.AzureCommunicationCalling#19]
Hi Thomas,

I am able to use your demo and able to do a video call but when I am using the same code with all the packages in another project solution then after generating token when I click on Call Group button, it is asking for permission, and after granting permission for everything, it throws this exception at this line:

_localVideoStream = new LocalVideoStream(camera, MainActivity.Instance);

Exception details:

{Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <94b04e1756104d1fa1d144932ae2720c>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <94b04e1756104d1fa1d144932ae2720c>:0 
  at AndroidX.Core.App.ActivityCompat.RequestPermissions (Android.App.Activity activity, System.String[] permissions, System.Int32 requestCode) [0x00057] in D:\a\1\s\generated\androidx.core.core\obj\Release\monoandroid9.0\generated\src\AndroidX.Core.App.ActivityCompat.cs:529 
  at EiMMessenger.Droid.ACS.CallingManager.JoinGroup (System.Guid groupID) [0x00002] in C:\Data\ChatApp\SmallBusinessApp(Chat App)\EMiChatAPP\EiMMessenger\EiMMessenger.Android\ACS\CallingManager.cs:46 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
	at crc64ee486da937c010f4.ButtonRenderer.n_onClick(Native Method)
	at crc64ee486da937c010f4.ButtonRenderer.onClick(ButtonRenderer.java:104)
	at android.view.View.performClick(View.java:7125)
	at android.view.View.performClickInternal(View.java:7102)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27336)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
}

All the project setting and versions are exactly same as the demo project but it's still not working.

Do you have any idea, how to fix it?

**Comment by tompi** [comment]
Hi @NeerajRai111 

Could you check your manifest file against the demo and see if you are missing something ?

**Comment by NeerajRai111** [comment]
Hi @tompi,
I have copied everything from demo to the new project manifest. The only difference is the name of the package.
![image](https://user-images.githubusercontent.com/38005036/119466491-4bbc2c00-bd62-11eb-92af-a26568bc5714.png)

**Comment by tompi** [comment]
Sorry, I didnt read the stacktrace properly last time. The problem is most likely that you are not setting the MainActivity.Instance on start. Check usages of that in my app and copy it in yours, it should be set when you start calling.

**Comment by NeerajRai111** [comment]
Thanks @tompi, 

I missed to write "Instance = this;" in OnCreate() function. It is working now!
